-- MySQL Script generated by MySQL Workbench
-- 04/01/17 23:18:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema curriculumbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curriculumbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curriculumbd` DEFAULT CHARACTER SET utf8 ;
USE `curriculumbd` ;

-- -----------------------------------------------------
-- Table `curriculumbd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`usuario` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `funcao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`cursos_complementares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`cursos_complementares` (
  `email` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `horas` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`email`, `curso`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`experiencia` (
  `email` VARCHAR(45) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `ano_entrada` INT(11) NULL DEFAULT NULL,
  `ano_saida` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`email`, `empresa`, `cargo`),
  CONSTRAINT `experiencia_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`formacao` (
  `email` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(75) NOT NULL,
  `instituicao` VARCHAR(75) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `conclusao` INT(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`, `curso`, `instituicao`),
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`idioma` (
  `email` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`, `idioma`),
  CONSTRAINT `idioma_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`info_adicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`info_adicional` (
  `email` VARCHAR(45) NOT NULL,
  `info_adicional` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `usuario_addinfo`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`personal_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`personal_info` (
  `email` VARCHAR(45) NOT NULL,
  `nomeCompleto` VARCHAR(50) NULL DEFAULT NULL,
  `idade` INT(11) NULL DEFAULT NULL,
  `sexo` VARCHAR(24) NULL DEFAULT NULL,
  `estadoCivil` VARCHAR(45) NULL DEFAULT NULL,
  `nacionalidade` VARCHAR(45) NULL DEFAULT NULL,
  `objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `curriculumbd`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculumbd`.`vote` (
  `email` VARCHAR(45) NOT NULL,
  `votes` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`email`),
  CONSTRAINT `email_votes`
    FOREIGN KEY (`email`)
    REFERENCES `curriculumbd`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
